### PR TITLE
Several minor fixes, make script non-verbose by default

### PR DESCRIPTION
**Pull request by neiser**
Several little fixes which make it work for me on travis-ci, also make the script non-verbose, which is useful for larger projects. Feel free to cherry-pick single commits if some of them are not usefule in your opinion. I'm also pretty unexperienced with code coverage testing, so some of the fixes might not be 100% correct.

### CODE REVIEW

**Comment by JoakimSoderberg** [comment]
Hello! Nice work. I like that you split it all up this nicely so I can pick and choose :)

The only one I don't like is the verbosity one. If you could change that to be optional. That is, in someway you have to explicitly tell it to be quiet, I will include it.

One idea would be to have a debug output function in a separate cmake script file that is included in the others. This function then checks if a global variable is set to be quiet (and outputs nothing) or otherwise prints the message passed to it.

I'm a bit busy and in vacation mode atm so I don't have time to check everything right now. Will look at it later though.

**Comment by neiser** [comment]
Hi! Well, as you wrote you may just pick the stuff you like, I just wanted to give some work back as you made the effort to have a nice Cmake-only coveralls upload. 

I probably won't implement to stuff to make it non-verbose as an option, since I found http://codecov.io which by the way is much easier to deploy on travis-ci :smile:

**Comment by JoakimSoderberg** [comment]
Well thank you again for the contribution, much appreciated... Especially the splitting up of commits like that :)

Oh nice that there's a new service... I've been kind of annoyed by the instability of coveralls, server timeouts and such. I might do a cmake script to make it as easy to use as well. If you haven't done that already that is?

**Comment by neiser** [comment]
Well, getting codecov.io to work is super-easy (much easier than coveralls): Just add

```
after_success:
  - bash <(curl -s https://codecov.io/bash)
```

to your `.travis.yml`. In the report, you can set some filters to get rid of unneeded files. See also https://codecov.io/guide

**Comment by JoakimSoderberg** [comment]
Ah ok... But don't you need to run gcov as well? Or is that done automatically somehow?

**Comment by JoakimSoderberg** [comment]
Anyway, I merged these changes manually without the verbose one.

Will try codecov.io later, thanks for the tip. I'll close this PR now :)

**Pull request closed without merging**
